---
title: "Masters of Data Science"
author: "Allen Miller"
date: "11/8/2020"
output: html_document
---

#About Me!

##Family
I am married to my best friend, Toni, and together we have 2 dogs. Leia, an Australian Shepard, is the happiest dog who just enjoys life to the fullest. Dodger, an Australian Shepard Toy-Poodle mix (Aussie-Doodle), loves to play and snuggle. We live in Fairbanks, AK and love the outdoors!

##Hobbies
I am a bit of a sports junkie, it doesn't really matter the sport or the teams I'm usually watching a game or following along. I love to run and have completed 3 full marathons and over 60 half marathons along with 5 Spartan Races (3-Sprints, 1-Super, 1-Beast).

##Professional
I am currently a SR Database Administrator for Lockheed Martin. I've served in many roles such as:
-Sr Database Admin
-Software Developer (Web Applications)
-Audio Visual Admin
-Data Network Technician
-Delivery Driver

##School
I am a graduate of Western Governor's University witha a Bachelor's in Software Development. Currently I am attending Southern Methodist University with studies focused in a Master's of Data Science.